### ISSUE TITLE
Virtual Host Manager Throws Undefined Index error

### ISSUE THREAD

**Issue by nheidgit** [easyphp/DEVSERVER#108]
Running a new install of EasyPHP 17.  Attempting to add Virtual Host Manager.  It immediately throws two line errors in the PHP files.  Will not allow adding any Virtual Hosts.  All files are installed in the C; directory of a Windows 10 machine.

Here is error thrown;
"  Virtual Hosts Manager 1.8
Notice: Undefined index: to in C:\EasyPHP-Devserver-17\eds-modules\virtualhostsmanager\virtualhostsmanager.php on line 390

Notice: Undefined index: add_vhost_error in C:\EasyPHP-Devserver-17\eds-modules\virtualhostsmanager\virtualhostsmanager.php on line 504"

**Comment by easyphp** [comment]
Hi. Ya, it's a bug. It's fixed now. Can you download Virtual Hosts Manager again  and test it ? It should be fine.

**Comment by nheidgit** [comment]
Errors that are thrown are now gone and the addition of the VHM looks to be OK when the Dashboard opens. It does not display any newly added virtual hosts however.  It appears as though no VHosts were added, hence unable to select from Dashboard.  The virtual host does show up in the "httpd-vhosts" file however.

**Comment by nheidgit** [comment]
Please note the prior comment.  I closed it by accident.

**Comment by easyphp** [comment]
Did you try to remove all Virtual Hosts and create them again ?

**Comment by jandw93** [comment]
Same issue here, just installed DevServer 17 and Virtual Host Manager 1.8
When I add a new vhost it doesn't appear in the dashboard, but VHM did add it to the httpd-vhost.conf

Next strange thing to happen is that when I manually remove the vhost from the httpd-vhost.conf file and I restart the http server it is added to the file again somehow (but still not visible in the dashboard).

It looks like VHM isn't recognizing vhosts from the httpd-vhosts.conf, but is able to add vhosts to it.
When there are vhosts in the file but not visible on the dasboard, then they're not working.

**Comment by jandw93** [comment]
After all I was able to get things working by running DevServer as Administrator.

**Comment by easyphp** [comment]
Fixed. A new version is out : Virtual Hosts Manager 2.0. This version needs Apache 2.4.48.
Download : https://warehouse.easyphp.org
